apiVersion: v1
kind: Secret
metadata:
  name: dogshelter-secret
  namespace: dogshelter
type: Opaque
stringData:
  username: dbUser
  password: dogshelter123
  pgadmin-email: admin@dogshelter.com
  pgadmin-password: pgadmin123
